### PR TITLE
Add new opp: QOSF Mentroship program and Los Alamos QC summer school

### PR DESCRIPTION
**Pull request by duarte-jfs**

### CODE REVIEW

**Comment by 1ethanhansen** [comment]
This is awesome! Can you make sure the new opportunities are in alphabetical order?

**Comment by duarte-jfs** [comment]
Sure thing, I'll do another PR in a minute

**Comment by duarte-jfs** [comment]
I just updated it. I don't really need to make another PR do I? It automatically saves the commits, right?

**Comment by abhobe** [comment]
Yes you do not need another PR.

**Comment by 1ethanhansen** [comment]
@labidon lgtm. I'm trying to get a contribution every day on github, so I'll merge this in tomorrow :)

**Comment by abhobe** [comment]
@1ethanhansen Is it possible I could merge this?

**Comment by 1ethanhansen** [comment]
@abhobe I think I'd prefer to do it, but thanks for offering :D

**Pull request merged**
